server:
  port: 5001

spring:
  application:
    name: spring-consumer-5001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://xtkj3001.com:3001/eureka,http://xtkj3002.com:3002/eureka

info:
  app:
    name: hello
  company: 讯腾科技
  build:
    artifactId: $aaa$
  version:  $project.version$